import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import {
  GridExample1,
  GridExample2,
  GridExample3,
  GridExample4,
} from "../styled-components/CSSGrid";

const CSSGrid: NextPage = () => {
  return (
    <>
      <Head>
        <title>CSSGrid</title>
        <meta name="description" content="Generated by COMMAND" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{
          width: "100%",
        }}
      >
        <>
          <h2>Example #kd92kd</h2>
          <GridExample1>
            <div className="item">
              1 Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam, quis nostrud exercitation ullamco laboris
              nisi ut aliquip ex ea commodo consequat.
            </div>
            <div className="item">2</div>
            <div className="item">3</div>
          </GridExample1>
        </>
        {/* <>
          <h2>Example 2</h2>
          <GridExample2>
            <div className="item">
              111asdfasdfasdfasdfasfasdf asdf asdf asdf
            </div>
            <div className="item">2</div>
            <div className="item">3</div>
            <div className="item">4</div>
          </GridExample2>
        </> */}
        <>
          <h2>Example #cmw029</h2>
          <GridExample3>
            <div className="item item-a">Header</div>
            <div className="item item-b">Main</div>
            <div className="item item-c">Sidebar</div>
            <div className="item item-d">Footer</div>
          </GridExample3>
        </>
        {/* <>
          <h2>Example 4</h2>
          <GridExample4>
            <div className="item item-1">1</div>
            <div className="item">2</div>
            <div className="item item-3">3</div>
            <div className="item">4</div>
            <div className="item item-5">5</div>
            <div className="item">6</div>
            <div className="item item-7">7</div>
            <div className="item">8</div>
            <div className="item item-9">9</div>
          </GridExample4>
        </> */}
      </main>
    </>
  );
};

export default CSSGrid;
