import type { NextPage } from "next";
import Head from "next/head";

import { useRef, useEffect } from "react";
import { gsap } from "gsap";
import { ScrollToPlugin } from "gsap/dist/ScrollToPlugin";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

import {
  Container,
  Section1,
  Section2,
  Section3,
  Up,
} from "../styled-components/GSAP";

import { ScrollToTop } from "../components/ScrollToTop";

const Gsap: NextPage = () => {
  const section1 = useRef();
  const section2 = useRef();
  const container = useRef<HTMLDivElement>();

  useEffect(() => {
    gsap.registerPlugin(ScrollToPlugin, ScrollTrigger);
  });

  return (
    <>
      <Head>
        <title>GSAP</title>
        <meta name="description" content="Generated by COMMAND" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container ref={container as any}>
        <Section1 className="section">
          <h3>Section #vjd92k</h3>
        </Section1>
        <Section3 className="section">
          <h3>Section #3jf03k</h3>
        </Section3>
        <Section2 className="section">
          <h3 className="head2">Section #dk3k1l</h3>
        </Section2>
        <ScrollToTop
          onClick={() => {
            gsap.to(container.current as any, { duration: 1, scrollTo: 0 });
          }}
        />
      </Container>
    </>
  );
};

export default Gsap;
