import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useState } from "react";

enum Lists {
  INLINE = "inline",
  BLOCK = "block",
}

function escapeHtml(text: string) {
  var map: {
    [key: string]: string;
  } = {
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&apos;",
  };

  const result = text.replace(/[&<>"']/g, function (m) {
    return map[m];
  });

  return <>{result}</>;
}
const InlineVsBlock: NextPage = () => {
  const [selectedList, setSelectedList] = useState<Lists>(Lists.INLINE);

  return (
    <>
      <Head>
        <title>Inline vs Block</title>
        <meta name="description" content="Generated by COMMAND" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header
        style={{
          textAlign: "center",
        }}
      >
        <h1>Inline vs Block</h1>
        <button
          onClick={() => {
            setSelectedList(Lists.INLINE);
          }}
        >
          Inline
        </button>
        &nbsp; versus &nbsp;
        <button
          onClick={() => {
            setSelectedList(Lists.BLOCK);
          }}
        >
          Block
        </button>
      </header>

      {selectedList === Lists.INLINE && (
        <>
          <h1>
            INLINE ELEMENTS - are html elements that take up only take up the
            width of their content meaning they allow multiple elements on the
            same line
          </h1>
          &lt;a&gt;&lt;abbr&gt;&lt;acronym&gt;&lt;b&gt;&lt;bdo&gt;&lt;big&gt;&lt;br&gt;&lt;button&gt;&lt;cite&gt;&lt;code&gt;&lt;dfn&gt;&lt;em&gt;&lt;i&gt;&lt;img&gt;&lt;input&gt;&lt;kbd&gt;&lt;label&gt;&lt;map&gt;&lt;object&gt;&lt;output&gt;&lt;q&gt;&lt;samp&gt;&lt;script&gt;&lt;select&gt;&lt;small&gt;&lt;span&gt;&lt;strong&gt;&lt;sub&gt;&lt;sup&gt;&lt;textarea&gt;&lt;time&gt;&lt;tt&gt;&lt;var&gt;
          <hr />
          <a href="#">Link to nowhere</a>
          <abbr>SKU</abbr>
          <b>That was bold</b>
          <br />
          <button>Press Me</button>
          <cite>CITATION</cite>
          <code>print(&#39;Hello, World!&#39;)</code>
          <em>EMPHASIS</em>
          <i>ITALICIZED</i>
          <img />
          <label>Label for the input following input</label>
          <input />
          <map>Where are we?</map>
          <select onChange={() => {}}>
            <option>1</option>
            <option>2</option>
            <option>3</option>
          </select>
          <small>TINY</small>
          <span>SPANNING MANY YEARS</span>
          <strong>EMPHASIS</strong>
          AU<sub>79</sub>E = mc<sup>2</sup>
          <time>11:11:11 PM</time>
        </>
      )}

      {selectedList === Lists.BLOCK && (
        <>
          <h1>
            BLOCK ELEMENTS - are html elements that take up the full width of
            the page
          </h1>
          &lt;address&gt;&lt;article&gt;&lt;aside&gt;&lt;blockquote&gt;&lt;canvas&gt;&lt;dd&gt;&lt;div&gt;&lt;dl&gt;&lt;dt&gt;&lt;fieldset&gt;&lt;figcaption&gt;&lt;figure&gt;&lt;footer&gt;&lt;form&gt;&lt;h1&gt;-&lt;h6&gt;&lt;header&gt;&lt;hr&gt;&lt;li&gt;&lt;main&gt;&lt;nav&gt;&lt;noscript&gt;&lt;ol&gt;&lt;p&gt;&lt;pre&gt;&lt;section&gt;&lt;table&gt;&lt;tfoot&gt;&lt;ul&gt;&lt;video&gt;&lt;/video&gt;
          <hr />
          <address style={{ display: "inline" }}>Miami, FL</address>
          <article>Award-winning Journalism</article>
          <aside>A sidenote to the main passage.</aside>
          <blockquote>This is a blockquote</blockquote>
          <canvas>I will show off canvas</canvas>
          <div>so generic and useful</div>
          <dd />
          <dl />
          <dt />
          <fieldset>Used to group elements</fieldset>
          <figcaption></figcaption>
          <figure>Have you figured it out yet?</figure>
          <footer>Usually on the bottom of you web UI</footer>
          <form>Used to collect information about your visitors</form>
          <h1>h1</h1>
          <h2>h2</h2>
          <h3>h3</h3>
          <h4>h4</h4>
          <h5>h5</h5>
          <h6>h6</h6>
          <header>
            A semantic element clearly describes its meaning to both the browser
            and the developer.
          </header>
          <hr />
          <li>an item of a list</li>
          <main>
            another semantic element for the main content on your page
          </main>
          <nav>another semantic element for the navigation on your page</nav>
          <noscript>console.log(&#39;WTF&#39;);</noscript>
          <ol>an ordered list</ol>
          <p>a paragraph of text</p>
          <pre>
            Text is displayed in a fixed-width font, and the text preserves both
            spaces and line break
          </pre>
          <section>another semantic element for a section on your page</section>
          <ul>an unordered list</ul>
          <video>Used to play video</video>
        </>
      )}
    </>
  );
};

export default InlineVsBlock;
